{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Last Measurement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last measurement",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Download",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Download",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last latency (ping + jitter)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Download",
     "measurement": "speedtest",
     "query": "SELECT last(\"ping\") + last(\"jitter\") FROM \"speedtest\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": ".",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Download Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Upload Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ping + jitter)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "speedtest",
     "query": "SELECT \"jitter\", \"ping\" FROM \"speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "jitter" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       { "params": [ "ping" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speedtest logs",
     "type": "table",
     "gridPos": { "h": 15, "w": 23, "x": 0, "y": 70 },
     "targets": [
      {
       "measurement": "speedtest",
       "query": "SELECT \"download\"  / 125000.00 AS \"Download Speed (Mbit)\", \"upload\"  / 125000 AS \"Upload Speed\", \"url\" AS \"URL\" FROM \"speedtest\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "download" ], "type": "field" },
         { "params": [ " / 125000.00" ], "type": "math" },
         { "params": [ "Download Speed" ], "type": "alias" }
        ],
        [
         { "params": [ "upload" ], "type": "field" },
         { "params": [ " / 125000" ], "type": "math" },
         { "params": [ "Upload Speed" ], "type": "alias" }
        ],
        [
         { "params": [ "url" ], "type": "field" },
         { "params": [ "URL" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}