# Generated by Django 3.2.12 on 2022-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220420_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuurl',
            name='post_request',
            field=models.BooleanField(default=False, null=True, verbose_name='Make this link a post request'),
        ),
    ]
