# Generated by Django 3.2.16 on 2022-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_menuurl_post_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuurl',
            name='post_warning',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
