# Generated by Django 3.2.16 on 2022-11-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_device_is_trusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='devices',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
