# Generated by Django 3.2.12 on 2022-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default=None, max_length=100, null=True, verbose_name='Server Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('entry_type', models.CharField(default='TEST', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('test_date', models.DateField(verbose_name='Test date')),
                ('duration', models.FloatField(default=0, verbose_name='Duration (s)')),
                ('data', models.TextField(default=None, null=True)),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='IP')),
            ],
            options={
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default=None, max_length=100, null=True, verbose_name='Server Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('entry_type', models.CharField(default='TEST', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('test_date', models.DateField(verbose_name='Test date')),
                ('duration', models.FloatField(default=0, verbose_name='Duration (s)')),
                ('data', models.TextField(default=None, null=True)),
                ('ping', models.FloatField(default=0.0, verbose_name='Average ping')),
                ('stats', models.CharField(max_length=100, verbose_name='Ping Values')),
                ('packet_loss', models.FloatField(null=True, verbose_name='Packet loss')),
            ],
            options={
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default=None, max_length=100, null=True, verbose_name='Server Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('entry_type', models.CharField(default='TEST', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('test_date', models.DateField(verbose_name='Test date')),
                ('duration', models.FloatField(default=0, verbose_name='Duration (s)')),
                ('data', models.TextField(default=None, null=True)),
                ('is_average', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('server_id', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Server ID')),
                ('latency', models.FloatField(default=None, null=True, verbose_name='Latency')),
                ('jitter', models.FloatField(default=None, null=True, verbose_name='Jitter')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='Download speed')),
                ('upload', models.PositiveIntegerField(default=0, verbose_name='Upload speed')),
                ('dl_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Downloaded bytes')),
                ('ul_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Uploaded bytes')),
                ('share_url', models.CharField(default=None, max_length=100, null=True, verbose_name='Share URL')),
            ],
            options={
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
    ]
